# Don't edit this file
#
# It was auto generated by cmake from project.json which should be edited instead

set(NAP_MODULES mod_napapp mod_napaudio mod_napaudioadvanced mod_spatialmonitor mod_nappython mod_naposc mod_naprender mod_napimgui mod_napnativefiledialog mod_napparameter)
